### ISSUE TITLE
Add full text search in more filters or advanced search

### ISSUE THREAD

**Issue by stevenvandervalk** [vecnet/dl-discovery#10]
Being able to pull more place names from the full text documents, pdfs etc.  Associate it with the document that it came from, etc.

**Comment by stevenvandervalk** [comment]
Not sure on the solr related difficulty of this yet - might make it into demo day but unlikely.

**Comment by dbrower** [comment]
There is a place holder full text field in the solr document, and it is _not_ automatically searched.

However, right now the field is mostly blank since the harvester has not been granted enough permissions to harvest full text from the DL. But there is an API key in place, and I just need to generate the tokens and configure the harvester. I see this happening after we get the deploy working.
