### ISSUE TITLE
figure out why times are showing up in place facet 

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#52]
figure out why times are showing up in place facet 
![image](https://cloud.githubusercontent.com/assets/3044754/7504117/a7d7104e-f415-11e4-8a86-766305bfc244.png)

**Comment by dbrower** [comment]
This is almost certainly a data quality issue, and the records are bad in fedora. The endnote ingest pulls location name and time period from the same endnote field. These dates are not in the right format, so they were treated as locations. They do not display in the original DL since they, being invalid, do not have a place in the geoname hierarchy, and hence do not show up in the hieratic all facet. This facet is not hierarical ,and is showing all the locations.

I can look at the records and fix them tomorrow. Also, the solr updating is not hooked up, so any changes will not be reflected in the discovery interface right now.

**Comment by dbrower** [comment]
There were 4 citations in QA, which I fixed by hand.

https://dl-dev.vecnet.org/catalog/mc87q195j
https://dl-dev.vecnet.org/catalog/hh63t659n
https://dl-dev.vecnet.org/catalog/j9602b316
https://dl-dev.vecnet.org/catalog/jd473715b

I'll update the solr index later today.

In production I found 3 citations with the same titles as the above, which I fixed by hand.
