### ISSUE TITLE
point label on hitlist display and placement of title string 

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#66]
Can we comment out display of GIS data type aka Point display on hitlist? 
Can we move title string to top left postion in list w/thumbnail under(see yellow highlighted titles in the screenshot of old system)?  Can hitlist items have a variable height so that hitlist items don't take up so much space or is it determined by thumbnail size? On the old one they were variable height(see red brackets in screenshot below) . 

![image](https://cloud.githubusercontent.com/assets/3044754/7993408/001c1c8e-0ad4-11e5-81cd-546e9165a3d6.png)

![image](https://cloud.githubusercontent.com/assets/3044754/7993621/6e2585b6-0ad5-11e5-9314-8925b8e4da9b.png)

**Comment by stevenvandervalk** [comment]
The point type tag was removed by 219b116d4f3582806e5b46c83b758ccef1886007.  Yes, the thumbnail height is influencing the height of the element and you don't want to resize those on the front end, I'll ask @dbrower  about them.  I've done a bunch of tricks to remove whitespace and minimise the height rather than changing the title location which is bad for grids and readability imo. Also added the tags related to sorting options which might also lessen white space.
![screenshot 2015-06-09 12 31 32](https://cloud.githubusercontent.com/assets/3012945/8049523/b7ad5a2a-0ea3-11e5-9c20-63b87d2af1a7.png)

**Comment by dbrower** [comment]
Yes, I removed the point tag. I saw an opportunity since i was in the file, and took it.

Could the thunbnails be moved to the right hand side? Also, why not resize the thumbnails using CSS (or HTML? not sure of the "right" way to do it.)

**Comment by stevenvandervalk** [comment]
Yep they can be on the right side.

Usually you prefer to pick a set of sizes and do the server side generation for performance and quality.  But if the thumbnails are still too large, you are completely right, we could CSS.

**Comment by stevenvandervalk** [comment]
Ah apologies @dbrower I only just realised what you are saying now about the right side;  to make the title on the top left.

![screenshot 2015-06-09 14 45 43](https://cloud.githubusercontent.com/assets/3012945/8050764/3e73a994-0eb6-11e5-8295-271adfaf0fbe.png)

**Comment by DanielBaird** [comment]
try switching the tag and thumbnail order, so goes:

```
    title title title         |  thumb  |  (<) 2013
    text text text text text  |  thumb  |  [A] Article
    text text text text       |  thumb  |  *>> PIE mmm pie
```

That might help with the slightly annoying whitespace 'twixt tag and thumbnail.

**Comment by stevenvandervalk** [comment]
![screenshot 2015-06-09 16 39 42](https://cloud.githubusercontent.com/assets/3012945/8052010/26bbe388-0ec6-11e5-8d7b-a8c2ef334802.png)
