### ISSUE TITLE
Try different UI elements for toggle map and search visible map area

### ISSUE THREAD

**Issue by stevenvandervalk** [vecnet/dl-discovery#81]
Based on feedback from Greg Madey.  Will put some screenshots and ideas in here.

**Comment by stevenvandervalk** [comment]
So his general point seems? lack of clarity current state + the action of the button.  

"Claim the state or don't use it. "Off" can mean click to turn off, or it means, "It is off now." That's crap." seems a common opinion in some UX circles.  

So, that rules out lots of modern styles but leaves us with explicit and simple which is fine e.g.

![screenshot 2015-06-18 14 07 47](https://cloud.githubusercontent.com/assets/3012945/8224097/bd4f6aa4-15c4-11e5-84fc-81a186dbd83d.png)
![screenshot 2015-06-18 14 07 55](https://cloud.githubusercontent.com/assets/3012945/8224098/bef98182-15c4-11e5-91b6-a0fe5d8da622.png)
![screenshot 2015-06-18 14 08 06](https://cloud.githubusercontent.com/assets/3012945/8224099/c05f3f8a-15c4-11e5-8e8a-ffa41fcb1319.png)

**Comment by stevenvandervalk** [comment]
So trying to show both the current state clearly and the proposed action :

![screenshot 2015-06-18 14 46 35](https://cloud.githubusercontent.com/assets/3012945/8224343/d78a2b80-15c8-11e5-9862-eb1b3b77e021.png)

So that rationale holds equally for the "search map button" so trying a single button with an explicit explanation :

![screenshot 2015-06-18 14 47 12](https://cloud.githubusercontent.com/assets/3012945/8224349/eca4f31a-15c8-11e5-980c-32a4426b1233.png)

**Comment by stevenvandervalk** [comment]
@dbrower thoughts?

**Comment by stevenvandervalk** [comment]
@nmyers Went with 

![screenshot 2015-06-18 16 43 04](https://cloud.githubusercontent.com/assets/3012945/8225519/1ba2793e-15d9-11e5-87d9-1947bb9c6154.png)

**Comment by stevenvandervalk** [comment]
Another idea suggested by Don is to add a Search Map Button tied to the original Search Bar.

**Comment by nkmeyers** [comment]
how about this toggle style? Replace "label" with "Show Map" ? 
![togglestylealternative](https://cloud.githubusercontent.com/assets/3044754/8240551/68508094-15d1-11e5-80d6-3ba9e9b990ea.JPG)

**Comment by nkmeyers** [comment]
here's what on-off states could look like, I think this might satisfy Greg's concern(s) re indicating current state? without going to a single button approach so you could still use a toggle element ?

![alt-toggle_offstate](https://cloud.githubusercontent.com/assets/3044754/8240843/84e4c754-15d3-11e5-8a01-8c3f58565bd7.jpg)

![alt-toggle_maponstate](https://cloud.githubusercontent.com/assets/3044754/8240848/88e20416-15d3-11e5-84f5-2cb8df79cc09.jpg)

**Comment by nkmeyers** [comment]
Let's change default state for Show Map to "ON" and try that for a while?

**Comment by nkmeyers** [comment]
can we implement "restrain search to visible map area only so that it is a checkbox associated with the default search button, and is  NOT an additional button?  - that way there'd be only one "search button"?  [same "search" also executes on hitting return/enter]   restraining to visible map area would work more like a "filter" then?   OR can we put the search map area button on top of the map itself? Earthworks below does it like that  . . . NOAA kinda does to but not so in your face - they just have a pencil icon  . . . 

And/or if we allowed "empty search screen = "all" and coupled it w/the checkbox to restrain then an empty search string w/the restrain to map area filter could/would perform just like "show all in visible map area"?

**Comment by nmyers** [comment]
Hi,
I think I've been to this thread by mistake. Thanks for removing my email from
it. Best
Nicolas

On Thu, Jun 18, 2015 at 21:08, vecnet/dl-discovery
reply@reply.github.com
wrote:
can we implement "restrain search to visible map area only so that it is a
checkbox associated with the default search button, and is NOT an additional
button? - that way there'd be only one "search button"? [same "search" also
executes on hitting return/enter] restraining to visible map area would work
more like a "filter" then?

if we allowed "empty search screen = "all" and coupled it w/the checkbox to
restrain then an empty search string w/the restrain to map area filter
could/would perform just like "show all in visible map area"?

—
Reply to this email directly or view it on GitHub
[https://github.com/vecnet/dl-discovery/issues/81#issuecomment-113275454] .[https://github.com/notifications/beacon/AAqUFGZh4-YNdnGg_kpvXOcvS-HIJiHuks5oUxzHgaJpZM4FFC29.gif]

**Comment by DanielBaird** [comment]
Sorry @nmyers, you were @mentioned and it's dragged you in.

I can't see a way for me to unsubscribe you, you probably need to go to the thread URL and click the unsubscribe button there:
https://github.com/vecnet/dl-discovery/issues/81

**Comment by DanielBaird** [comment]
Probably any kind of sliding-toggle element will have the same problem as the current one -- tension between showing current state vs. showing interaction outcome.  If it's showing you an "off" symbol like a red cross, does that mean it's on now, and you click the red cross to switch it off?  Or does showing the red cross mean it's off now, and you should click it to change to on?

The emerging convention is that the thing showing is how it is NOW, and you click it to change it.  I expected that having toggle buttons on mobile devices would mean everyone was familiar with how they work, but if Greg isn't, we should avoid the problem with a radio button setup.

Restraining search to the map area could be a checkmark that stays checked.  It seemed simpler to have a "narrow down these results by showing just the ones that fit on the map" button that just did an instant winnowing.  Having it as a persistent filter is awkward because of auto-zoom -- if the map bounds are a search filter, we can't autozoom any more (because it would be messing with the user's search setting), and there will be map points that aren't in view (because results with only one of their five points in the search area will be included but you won't see the four other points).

**Comment by nkmeyers** [comment]
What can we do to eliminate having two search buttons on one "form"  - it is still unclear what happens to the text string search if you choose the second button instead of the "first"? 

Is there some technical reason why it has to be two buttons? I noticed Stanford's Branner map library implements this a little differently than we are, but still with two buttons but in a way that's a little less "conflicted" by using Browse labels at top search screen and a way of representing filters after map search on results page.  See: https://earthworks.stanford.edu/

On default search screen there are 2 buttons like ours (numbered in red). 

![image](https://cloud.githubusercontent.com/assets/3044754/8432184/7956b464-1f0c-11e5-899d-4b009957227c.png)

But after searching "by map" their results page has more filter and map options - also makes user aware that they DID a bounding box search - the "you searched for" info is presented on screen. They DO NOT attempt to paint search results to the screen. 

![image](https://cloud.githubusercontent.com/assets/3044754/8432302/3fec4468-1f0d-11e5-9430-37754d50c8d4.png)

**Comment by nkmeyers** [comment]
NOAA has a different approach  .  Default search page shows count of ALL data.  Then user searches and the number goes down. User is aware from start how many records are avail. 

Rather than two buttons they have a magnifying glass icon on the text search bar (see blue circle). 

See also how  their map filter features to the left of the search bar(2 of them are annotated in red). 

The location only search can be done with a separate text string tied to place names OR  with a map "filter" where the user draws a box after clicking a pencil icon. Like stanford they do not attempt to draw search results to the map on the results page.  

![image](https://cloud.githubusercontent.com/assets/3044754/8432633/3d9fae5a-1f0f-11e5-85e0-206f1d67311b.png)

![image](https://cloud.githubusercontent.com/assets/3044754/8432563/d3b7f51a-1f0e-11e5-977a-d842828fabee.png)

![image](https://cloud.githubusercontent.com/assets/3044754/8432486/6d0fe142-1f0e-11e5-95df-708906871423.png)

**Comment by nkmeyers** [comment]
What the above makes me wonder a bit is whether some of what our bargain of using map as filter and map as results list buys us out of continuing to use map as filter after first hits are displayed. I think I am ok with that, anyone else have an opinion?

**Comment by nkmeyers** [comment]
here's another one for comparison's sake - from usgs http://ngmdb.usgs.gov/ there's only one search button but the "use area shown on map" selection (w/a checkbox) works like our map search . . . .

Here zooming to a map area works like on our implementation, but there is immediate onscreen notification to user about what search criteria are, and how they filter the overall set of records.  In Red see how I zoomed to kenya/somalia and in yellow/red see how that selection info is communicated back to user both with map coordinates, bounding coordinates, and search count display . . . .

![image](https://cloud.githubusercontent.com/assets/3044754/8436943/cd1778b4-1f29-11e5-8052-dde7f3521391.png)

**Comment by stevenvandervalk** [comment]
Ok I've replaced button with checkbox and implemented it as a restriction to the normal search action, including any other terms and facets put in.   

<img width="1175" alt="screenshot 2015-07-20 13 45 01" src="https://cloud.githubusercontent.com/assets/3012945/8769663/905c1184-2ee5-11e5-9dd5-981da8efa8ae.png">

<img width="704" alt="screenshot 2015-07-20 13 45 44" src="https://cloud.githubusercontent.com/assets/3012945/8769664/a726f460-2ee5-11e5-88f4-8a2eed122973.png">

https://github.com/vecnet/dl-discovery/pull/100
I've added an issue to create some UI user feedback for the coordinates as I agree that would be good but a few other items are more pressing. https://github.com/vecnet/dl-discovery/issues/101

**Comment by stevenvandervalk** [comment]
@nkmeyers I've prototyped a little UI element that shows the current map bounding box and automatically updates as the map pans - to give feedback to the user.  Hopefully that is helpful. It can be  reworded to 'Visible map' or something. Or removed easily.

<img width="682" alt="screenshot 2015-07-08 20 52 59" src="https://cloud.githubusercontent.com/assets/3012945/8568691/705d6576-25b3-11e5-9fa9-65a13cc547a6.png">
