### ISSUE TITLE
tidy up UI empty space and redundant or conflicting elements

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#96]
can we continue to tidy up UI white space and eliminate redundant or conflicting elements?

Green arrows show white space I wonder if we could narrow so that more of site is "above the fold". 

Can the Map ON/OFF button be moved left aligned w/the left side of search box ? 

Can we eliminate the label "Map"  that comes before the Map On/Off buttons ? did you leave on backburner or discard my map slider UI control graphic idea in favor of the buttons? If so, ok but with their prominent labels we no longer need the other "Map" label. 

It is still unclear/confusing  to the user if "Search Map" restricts, replaces or somehow otherwise complements the text based search string. 

Can there please be only one search button on the page with the restrict search to map area feature implemented as a "Limit search to Visible Map Area" check box or something (if indeed that's how its working)?  

![image](https://cloud.githubusercontent.com/assets/3044754/8431811/ede1afee-1f09-11e5-9a6e-c116d1e22dd2.png)

**Comment by stevenvandervalk** [comment]
Summary : Yes.  Less whitespace, one search button with checkbox and no to realignment.

1) Yes we can!

2) Yes, I'll go removing more whitespace :) 

3) No, that will totally ruin the grid structure.

4) Same as 3, IMO removing just that label makes the rest of the labels and grid inconsistent. But if you are set on that, it was a lot of layout hackery that I would rather not repeat...

5) Backburner. After all the discussion this option caused, a black and white option instead of a 'toggle' element seemed most likely to prevent any further confusion.

6) Yes I agree. I'll remove the second search option and add a checkbox for "Limit search to Visible Map Area"

**Comment by stevenvandervalk** [comment]
1 2  and 6 implemented.
https://github.com/vecnet/dl-discovery/pull/100
https://github.com/vecnet/dl-discovery/pull/103
